name: Build LaTeX document
on: [push]
permissions: 
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: courthouse_scenario.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf
      - name: Release the pdf file
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./courthouse_scenario.pdf            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

